version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: 'cimg/openjdk:21.0.2'
    steps:
      - checkout
      - run:
          name: Run tests and send coverage to Coveralls
          command: mvn cobertura:cobertura coveralls:report -DrepoToken=COVERALLS_REPO_TOKEN
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=astolstov1bit_UIVPRPO_regexProj -DskipTests=true


workflows:
  main:
    jobs:
      - build:
          context: SonarCloud