version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.1
  jobs:
    build:
      working_directory: ~/project
      docker:
        - image: 'cimg/openjdk:21.0.2'
      steps:
        - checkout
        - coveralls/upload
        - run:
            name: Analyze on SonarCloud
            command: mvn verify sonar:sonar -Dsonar.projectKey=astolstov1bit_UIVPRPO_regexProj -DskipTests=true


workflows:
  main:
    jobs:
      - build:
          context: SonarCloud